"""UTSM Telemetry analysis package.

Shared helpers for GPX parsing, telemetry ingestion, lap splitting,
GPS/telemetry alignment, and energy-channel derivation.  Both
gps_current_heatmap.py and analyze_strategy.py import from here.
"""

from .core import (
    NAMESPACE,
    GRAVITY_M_S2,
    FORWARD_AXIS_CHOICES,
    parse_iso8601,
    parse_lap_time,
    read_gpx,
    read_telemetry,
    add_xy,
    add_gps_motion_features,
    find_start_spike,
    find_nearest_gps_index,
    find_lap_boundaries_by_y_crossing,
    find_lap_boundaries_by_start_gate,
    count_line_crossings,
    detect_lap_line,
    compute_distance,
    compute_lap_stats,
    split_gps_into_laps,
    align_telemetry,
    merge_by_time,
    derive_acceleration_features,
    add_gps_acceleration_features,
    compute_accel_candidate_scores,
    derive_motion_energy,
)
from .simulation import (
    ACTION_ACCELERATE,
    ACTION_HOLD,
    ACTION_COAST,
    DEFAULT_MOTOR_PROFILE,
    build_motor_config,
    infer_gear_ratio,
    classify_strategy_action,
    build_full_run_distance,
    build_strategy_segments,
    fit_empirical_energy_model,
    predict_current_mA,
    predict_power_w,
    optimize_speed_profile,
    build_strategy_samples,
    evaluate_baseline_prediction,
    build_strategy_report,
)

__all__ = [
    "NAMESPACE",
    "GRAVITY_M_S2",
    "FORWARD_AXIS_CHOICES",
    "parse_iso8601",
    "parse_lap_time",
    "read_gpx",
    "read_telemetry",
    "add_xy",
    "add_gps_motion_features",
    "find_start_spike",
    "find_nearest_gps_index",
    "find_lap_boundaries_by_y_crossing",
    "find_lap_boundaries_by_start_gate",
    "count_line_crossings",
    "detect_lap_line",
    "compute_distance",
    "compute_lap_stats",
    "split_gps_into_laps",
    "align_telemetry",
    "merge_by_time",
    "derive_acceleration_features",
    "add_gps_acceleration_features",
    "compute_accel_candidate_scores",
    "derive_motion_energy",
    "ACTION_ACCELERATE",
    "ACTION_HOLD",
    "ACTION_COAST",
    "DEFAULT_MOTOR_PROFILE",
    "build_motor_config",
    "infer_gear_ratio",
    "classify_strategy_action",
    "build_full_run_distance",
    "build_strategy_segments",
    "fit_empirical_energy_model",
    "predict_current_mA",
    "predict_power_w",
    "optimize_speed_profile",
    "build_strategy_samples",
    "evaluate_baseline_prediction",
    "build_strategy_report",
]
